### ISSUE TITLE
Split data file into smaller chunks.

### ISSUE THREAD

**Issue by tanzir71** [SimFin/bd-extractor#6]
The following file contains 1500+ companies with financial data. https://simfin.com/data/access/download

I am trying to split the files by N number of companies (i.e. file1 contains 30 companies, file2 has 30, so on...) to upload it into my Django project. There are too many columns and rows and I get an error that the data exceeds the capacity of the database.

What is the best way to do this in Python?

Tried the following code.

```
import sys
import csv
from extractor import *

csv.field_size_limit(sys.maxsize)

datasetFull = SimFinDataset('new-data.csv','semicolon')

filename = 1

for i in range(datasetFull.numCompanies):
    if i % 30 == 0:
        f = open(str(filename) + '.csv','w')
        for a in range(i, i+30):
            j = datasetFull.companies[a]
            f.write(j)
        f.close()
        filename += 1
```
Output does not retain the same format as CSV. Plus data values need to be called.

**Comment by thf24** [comment]
I think in that case you might be better off just manipulating the original CSV file withouth using the extractor (as the extractor creates the company objects, but you just want to split the CSV in several parts I think).
You can slice the original CSV in several parts knowing how many indicators you have in the data file (i.e. ratios/fundamental figures for each company), you can find that out by running "print datasetFull.numIndicators". That info together with datasetFull.numCompanies is enough information to split the CSV I think (the CSV has datasetFull.numIndicators * datasetFull.numCompanies + 1 columns, the first column being the dates, that's why +1)

**Comment by tanzir71** [comment]
I know, that's what I thought too, but there's also dates set as columns, not just indicators. Anyway, let me start over and see what I can do. If anyone has a better idea, please let me know. I don't know how the data or extractor is being used by anyone else -- but splitting into chunks seems like some basic functionality anyone who uses the data would need.

**Comment by ranm** [comment]
I would do something else : use the extractor and dump each group of 30 companies into a new CSV with whatever formatting as you want and upload that to your system. Or you can build a ״reverse formator״ if you want to keep the same format as simfin’s . 

Ran.
    On Tuesday, April 24, 2018, 2:59:12 AM GMT+3, Tanzir Rahman <notifications@github.com> wrote:  
 
 
I know, that's what I thought too, but there's also dates set as columns, not just indicators. Anyway, let me start over and see what I can do. If anyone has a better idea, please let me know. I don't know how the data or extractor is being used by anyone else -- but splitting into chunks seems like some basic functionality anyone who uses the data would need.
